name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.8', '3.10']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip
          pip install -e .
          pip install flake8
      - name: Style check
        run: flake8
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.8', '3.10']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip
          pip install -e .[generative,examples]
          pip install pytype
      - name: Type check adaptor
        run: pytype adaptor
      - name: Type check utils
        run: pytype utils
      - name: Type check unit tests
        run: pytype tests
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.8', '3.10']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip
          pip install -e .[generative]
          pip install pytest
      - name: Unit tests
        run: cd tests && pytest .
